### ISSUE TITLE
Problem initiating registration

### ISSUE THREAD

**Issue by gtfioreze** [SainsburyWellcomeCentre/amap-python#46]
Hi Adam,
First thanks for developing this tool.
I am interested in using it on my dataset but I run into errors when trying to run. I have my images (.jpg) saved in a folder and this is the command I run at anaconda prompt:
['X:\\Histology\\GF343\\testAMAP', 'X:\\Histology\\GF343\\testAMAPoutput', '-x', '0.65', '-y', '0.65', '-z', '100', '--flip-y', '--flip-z']

And get this error:
Traceback (most recent call last):
  File "c:\users\user\anaconda3\envs\amap\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user\anaconda3\envs\amap\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\USER\Anaconda3\envs\amap\Scripts\amap.exe\__main__.py", line 7, in <module>
  File "c:\users\user\anaconda3\envs\amap\lib\site-packages\amap\cli.py", line 415, in main
    run()
  File "c:\users\user\anaconda3\envs\amap\lib\site-packages\amap\cli.py", line 393, in run
    debug=args.debug,
  File "c:\users\user\anaconda3\envs\amap\lib\site-packages\amap\main.py", line 99, in main
    n_free_cpus=n_free_cpus,
  File "c:\users\user\anaconda3\envs\amap\lib\site-packages\amap\register\brain_processor.py", line 88, in __init__
    n_free_cpus=n_free_cpus,
  File "c:\users\user\anaconda3\envs\amap\lib\site-packages\brainio\brainio.py", line 79, in load_any
    n_free_cpus=n_free_cpus,
  File "c:\users\user\anaconda3\envs\amap\lib\site-packages\brainio\brainio.py", line 194, in load_from_folder
    paths, x_scaling_factor, y_scaling_factor, n_free_cpus=n_free_cpus
  File "c:\users\user\anaconda3\envs\amap\lib\site-packages\brainio\brainio.py", line 285, in threaded_load_from_sequence
    stack = np.dstack([s.result() for s in stacks])
  File "<__array_function__ internals>", line 6, in dstack
  File "c:\users\user\anaconda3\envs\amap\lib\site-packages\numpy\lib\shape_base.py", line 721, in dstack
    return _nx.concatenate(arrs, 2)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate

Do you have an idea of what could it be?

Thank you very much in advance!

**Comment by adamltyson** [comment]
I'm not sure. What is the structure of your input data (single file, series of tiffs etc?)

If you can send me some test data, I can try to reproduce.

**Comment by gtfioreze** [comment]
It's a series of jpgs each spaced 100um in z. do they need to be in tiff?

**Comment by adamltyson** [comment]
Yes, currently cellfinder only reads tiffs. 

P.S. jpegs aren't great for data analysis

**Comment by gtfioreze** [comment]
Thank you, that error was solved.
However I bumped into another one... and I wonder if the problem it's the nature of my data.
Do you think I could send you a test dataset?
Thanks

**Comment by adamltyson** [comment]
Yep, just send it Adam.tyson@ucl.ac.uk and I’ll take a look

**Comment by gtfioreze** [comment]
ok! thanks!
